"""empty message

Revision ID: 77d012e9c6f0
Revises: 5c470bc4fa6d
Create Date: 2024-11-12 22:31:25.211137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77d012e9c6f0'
down_revision = '5c470bc4fa6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture_path', sa.String(), nullable=True))
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('picture_path')

    # ### end Alembic commands ###
