"""empty message

Revision ID: fb6b99be8b3b
Revises: 77d012e9c6f0
Create Date: 2024-11-13 07:25:15.196519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb6b99be8b3b'
down_revision = '77d012e9c6f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.Boolean(), nullable=True))
        batch_op.drop_column('picture_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture_path', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('picture')

    # ### end Alembic commands ###
